es:
  ip_address: 47.98.255.147
  port: 9200

alphavantage:
  apikey:
    - 9Z5P8Q65555NYU47
    - R90YBA1SXDJH1E34
    - 2QMA8UENCX9LX7ZR
  url: https://www.alphavantage.co/query?

companys:
  - A
  - AA
  - AA_
  - AA.
  - AA_B
  - AA.B
  - AAAP
  - AAAU
  - AABA
  - AAC
  - AACC
  - AADR
  - AAIT
  - AAL
  - AAMC
  - AAME
  - AAN
  - AAOI
  - AAON
  - AAP
  - AAPC
  - AAPL
  - AAPL22
  - AAPL24
  - AAPL25
  - AAPL26
  - AAPL27
  - AAPL29
  - AAPL29A
  - AAPL42
  - AAT
  - AAU
  - AAV
  - AAVL
  - AAWW
  - AAXJ
  - AAXN
  - AB
  - ABAC
  - ABAX
  - ABB
  - ABBV
  - ABC
  - ABCB
  - ABCD
  - ABCO
  - ABCW
  - ABDC
  - ABE
  - ABEO
  - ABEOW
  - ABEV
  - ABG
  - ABGB
  - ABIL
  - ABILW
