es:
  ip_address: 192.168.231.146
  port: 9200

alphavantage:
  apikey:
    - 9Z5P8Q65555NYU47
    - R90YBA1SXDJH1E34
    - 2QMA8UENCX9LX7ZR
  url: https://www.alphavantage.co/query?

companys:
  - TCEHY
  - TCTZF
  - TME
  - BABA
  - BABAF
  - ALBBY
  - ALBHF
  - BIDU
  - BAIDF
  - BILI
  - BLBLF
  - CCIHY
  - CNET
  - CNTFY
  - FUTU
  - IQ
  - JDID
  - MOMO
  - NCTY
  - NTES
  - OIIM
  - QTT
  - SINAX
  - SOHU
  - TIGR
  - TOUR
  - UTSI
  - VIOT
  - VNET
  - WB
  - XNET
  - YY
  - YYYH
  - CAAS
  - GIGM
  - HIMX
  - HLG
  - HTHT
  - KGJI
  - NVFY
  - PDD
  - CJJD
  - CHNR
  - VIPS
  - ATHM
  - SMI
  - HUYA
  - RENN
  - MOGU
  - EDU
  - NIO
  - SHI
  - CHL
  - CHT
  - CEA
  - ZNH
  - TSM
  - CHAEF
  - CHBU
  - CIDHF
  - CIDHY
  - CHMCF
  - CFRLF
  - SBHMY
  - SBMFF
  - OILY
  - SNAS
  - CPHI
  - QFIN
  - LFCHY
  - ZTO
  - CALIQ
  - LX
  - LXEH
  - XNGIF
  - SVA
  - CREG
  - JASNQ
  - CJJD
  - YIHG
  - HTHT
  - KGJI
  - CAAS
  - UXIN
  - BGNE
  - BSPM
  - CBAT
  - CREG
  - FFHL
  - NIU
  - PUYI
  - YJ
  - YJGJ
  - FENG
  - LEJU
  - CMCM
  - DOYU
  - ZH
  - XIACY
  - SHI
