es:
  ip_address:
    - http://tc405-112-01.insa-lyon.fr:9400
    - http://tc405-112-02.insa-lyon.fr:9400
    - http://tc405-112-03.insa-lyon.fr:9400
    - http://tc405-112-04.insa-lyon.fr:9400
    - http://tc405-112-05.insa-lyon.fr:9400
    - http://tc405-112-06.insa-lyon.fr:9400
    - http://tc405-112-07.insa-lyon.fr:9400
    - http://tc405-112-08.insa-lyon.fr:9400
    - http://tc405-112-09.insa-lyon.fr:9400
    - http://tc405-112-11.insa-lyon.fr:9400
    - http://tc405-112-12.insa-lyon.fr:9400

alphavantage:
  apikey:
    - SEMFKEB4GNRCLDIN
    - P7145QPWOJ8V8HP7
    - B7MFHYK85TIZ85G3
    - 9Z5P8Q65555NYU47
    - R90YBA1SXDJH1E34
    - 2QMA8UENCX9LX7ZR
    - 6PUFO6JT2DEKTY6B
  url: https://www.alphavantage.co/query?

companys:
  - AAAU
  - AABA
  - ABAX
  - ABC
  - ACAM
  - ACPW
  - ACT.A
  - ACWV
  - ACY
  - ADGE
  - AEL
  - AES_C
  - AEV
  - AFSS
  - AGGY
  - AGOL
  - AHT.A.CL
  - ALDX
  - ALL_H
  - AMAG
  - AMFW
  - AMOM
  - AND
  - ANDAU
  - ANFI
  - ANIP
  - APD
  - APDNW
  - APO_A
  - APOL
  - AREX
  - ARI.C
  - ASC
  - ASEA
  - ASPS
  - ASPU
  - ASRT
  - AVH
  - AXDX
  - AXJS
  - AXSM
  - AZN
  - BAC.W.CL
  - BAC_WS_A
  - BBC
  - BBJP
  - BCML
  - BDN_E_CL
  - BECN
  - BELFA
  - BGE_B
  - BGX
  - BHACW
  - BIP
  - BIR_A
  - BJAN
  - BLDP
  - BLU
  - BLX
  - BML.H
  - BML_J
  - BMLA
  - BOLT
  - BRKR
  - BRPAU
  - BRXX
  - BSJK
  - BVAL.NASDAQ
  - BWZ
  - BXMT
  - CANE
  - CATS
  - CBB.B
  - CBND
  - CBPX
  - CCH_WS
  - CCMP
  - CCS
  - CDNS
  - CDVI
  - CERC
  - CFG_D
  - CGC
  - CHDX
  - CHNGU
  - CHUY
  - CI
  - CIBR
  - CID
  - CIFC
  - CIM_D
  - CJES
  - CLCD
  - CLDC
  - CLDR
  - CLGN
  - CLNS.A
  - CLNY_C
  - CLNY.J
  - CLRBW
  - CLX
  - CMD
  - CMRE_C
  - CNSL
  - CNXT
  - COF_P
  - COT
  - CPT
  - CRDS
  - CROP
  - CRSP
  - CSTR
  - CTNN
  - CVSL
  - CWS.NASDAQ
  - DAX
  - DBES
  - DBMX
  - DCP_C
  - DCTH
  - DEL
  - DF
  - DFNL
  - DFVS.NASDAQ
  - DGLT
  - DLGC
  - DLHC
  - DLR.F.CL
  - DLR.H.CL
  - DLR.J
  - DMTKW
  - DORM
  - DOTAW
  - DRA
  - DS.B
  - DSCO
  - DTUL
  - DVAX
  - DWTI
  - DXM
  - DXR
  - DXUS
  - DZK
  - EAC
  - ECC
  - ECOM
  - EDBI
  - EDI
  - EE
  - EEMV
  - EFAS
  - EFFE
  - ELA
  - ELMD
  - ELS.C.CL
  - EMP
  - EMRE
  - ENB
  - EQLT
  - ERIE
  - ESE
  - ESGG
  - EURL
  - EURN
  - EWW
  - EWZ
  - EXFO
  - EXIV
  - EXPCW
  - EXTN
  - FBG
  - FBIOP
  - FCCY
  - FCEL
  - FCZA
  - FDD
  - FDP
  - FFBH
  - FKO
  - FLAG
  - FLLC
  - FMBI
  - FNBG
  - FNF
  - FNFG_B
  - FNGD
  - FNGO
  - FNK
  - FPO_A
  - FPP_WS
  - FRBA
  - FRC_H
  - FREEF
  - FST
  - FSV
  - FTDR
  - FXI
  - FXSG
  - GAZB
  - GCV
  - GDVD
  - GECXU
  - GEQ
  - GGOV
  - GIL
  - GJT
  - GLAC
  - GLBY
  - GLIBA
  - GLIBB
  - GLOP_C
  - GLOP.C
  - GNE_A
  - GOLD_NYSE
  - GOM
  - GOODP
  - GOVN
  - GPAC
  - GRX
  - GST_A
  - GUNR
  - GURE
  - HABT
  - HACK
  - HAWKB
  - HBNK
  - HCFT_A_CL
  - HDV
  - HHS
  - HITK
  - HL_B
  - HLACW
  - HPP.B
  - HRL
  - HSBC_A
  - HTFA
  - HTY
  - HTZRTWI
  - HUSI.G
  - HUSI_H
  - HZO
  - IBCPO
  - IBKCP
  - IBMN
  - ICC
  - ICUI
  - IDI
  - IDRV
  - IGLE
  - IGT
  - IMMU
  - INFU
  - INV
  - IPHI
  - IPXL
  - IRBT
  - IRDMU
  - ISBC
  - ISH.B
  - ISHG
  - ITEQ
  - ITIC
  - ITUB
  - IUSB_NASDAQ
  - IWS
  - JKI
  - JMIN
  - JMOM
  - JMPD
  - JPM.A
  - JRCCQ
  - JRS_NYSE
  - JST
  - KCAP
  - KCLI
  - KF
  - KFI_CL
  - KGC
  - KKR
  - KMF
  - KMPA
  - KOOL
  - KOPN
  - KREF
  - KRG.A
  - KYN.G
  - LBRDK
  - LCAV
  - LEDR
  - LEND
  - LGCYP
  - LILAB
  - LILKV
  - LIQT_NASDAQ
  - LMBS
  - LMOS
  - LND
  - LOB
  - LOU_U
  - LPSB
  - LQD
  - MASC
  - MCLB
  - MCRB
  - MDLQ
  - MEMS
  - MFM
  - MFV
  - MG
  - MGEN
  - MHO.A
  - MITO
  - MKF
  - MMC
  - MMTC
  - MMU
  - MNGA
  - MNR_B
  - MONT
  - MOVE
  - MRKT
  - MTB_CL
  - MTL_
  - MULT
  - MVIN
  - MWK
  - MWO_CL
  - MXMTY
  - MYE
  - NAD
  - NCTY
  - NCZ.A
  - NETL
  - NGVC
  - NHC_A_CL
  - NI.B
  - NIU
  - NLY
  - NLY.D
  - NMA
  - NSAT
  - NTGN
  - NUVA
  - NWL.NYSE
  - NYRT
  - OAC_U
  - OAC.WS
  - OBOT
  - OEF
  - OIBRR
  - OILX
  - OISC
  - ONCS
  - ONEK
  - ONG
  - OQAI
  - OVRL
  - OVTI
  - OXLCO
  - PACEW
  - PBCTP
  - PCG.E
  - PCS
  - PE
  - PEBK
  - PG
  - PGHEF
  - PI
  - PIOI
  - PKW
  - PLMR
  - PNI
  - PPDM
  - PPX
  - PRAH
  - PRK
  - PRMW
  - PRTH
  - PSB_S
  - PSEC
  - PSTG
  - PSTVZ
  - PVI
  - PVTD
  - PXE
  - PXLW
  - QBAK
  - QCP
  - QDXU
  - QTEC
  - QTS
  - QUMU
  - QXGG
  - QXMI
  - RAX
  - RBBN
  - RBS.R
  - RCG
  - RCKY
  - RCMT
  - RFI
  - RGEN
  - RGS
  - RLGT_A
  - RLH.A
  - RLJ
  - RMAX
  - RMD
  - ROCK
  - RRGB
  - RTNB
  - RXN_A
  - RY.T
  - SAMG
  - SAN.C
  - SAN_I
  - SBR
  - SBRAP
  - SBW
  - SCG
  - SCHG
  - SCIJ
  - SCO
  - SCTO
  - SDR
  - SFLY
  - SGK
  - SGZA_CL
  - SITC
  - SLAB
  - SLRA
  - SLW
  - SNI
  - SNLN.NASDAQ
  - SNPE
  - SOLY
  - SPAQ
  - SPFI
  - SPG.J
  - SPNE
  - SPUU
  - SRUNU
  - STAR.G
  - STCK
  - STEM
  - STIP
  - STRM
  - STS
  - STZ/B
  - SUN
  - SUPX
  - SUSL
  - SWNC
  - SYMX
  - SYRG
  - SYRX
  - SYSW
  - SYTL
  - SZMK
  - TAI
  - TBPH
  - TCAP
  - TCBIP
  - TCO_J
  - TCO.J
  - TDW
  - TECH
  - TECU
  - TEO
  - TER
  - TESO
  - TFSL
  - TGE
  - THCB
  - THCX
  - THNX
  - TIGO
  - TILT
  - TKMR
  - TLP
  - TLRA
  - TMK.B
  - TMSRW
  - TORMA
  - TOTA
  - TPVZ_CL
  - TRK
  - TSLX
  - TUC
  - TUTI
  - TVTY
  - TWER
  - TWMC
  - TWNK
  - TWTC
  - TYYPA
  - UBER
  - UPWK
  - URGN
  - UTSL
  - UUU
  - UZC
  - VALQ
  - VDSI
  - VHS
  - VJET
  - VLP
  - VNO_J
  - VRA
  - VREX
  - VSPY
  - WAGE
  - WANT
  - WATT
  - WBIK
  - WBS.WS
  - WCRX
  - WEN
  - WFC_O
  - WIFI
  - WIZE
  - WMC
  - WMLP
  - WPZ
  - WSBF
  - WSO/B
  - XIVH
  - XLC
  - XSVM
  - YCBD
  - YOKU
  - YORW
  - Z
  - ZAHLY
  - ZB_F_CL
  - ZB_H
  - ZHOK
  - ZM
  - AAON
  - AAPL22
  - ACC
  - ACERW
  - ACMR
  - ACW
  - ACWX
  - ADMP
  - AED_CL
  - AEGN
  - AEL
  - AFGL
  - AFMD
  - AGM
  - AGMH
  - AGN.A
  - AHT.H
  - AIII
  - AIRI
  - AIRWV
  - ALO
  - ALTR
  - AMLX
  - AMRN
  - AMSF
  - AMT_A
  - AND
  - APPN
  - APY
  - ARCW
  - ARDX
  - ARIS
  - ARKG
  - ASB_WS
  - ASRVP
  - ATMP
  - AVG
  - AXLL
  - AXPWW
  - ...
  - BAC_B
  - BAC_M
  - BARL
  - BBAX
  - BCI
  - BCV
  - BEN
  - BFIT
  - BFY
  - BHFAP
  - BHLB
  - BIG
  - BIL
  - BIP
  - BIRT
  - BIZD
  - BLBDW
  - BLL
  - BLV
  - BNDC
  - BROG
  - BSE
  - BTX
  - BUD
  - BV
  - BXP.B
  - BZM
  - BZUN
  - C_J
  - CAA
  - CADC
  - CAPX
  - CARE
  - CBB
  - CCL
  - CCS
  - CDOR
  - CDTX
  - CEB
  - CEE
  - CEF
  - CELP
  - CFCOU
  - CFXA
  - CHAC.U
  - CHK.D
  - CHUY
  - CHY
  - CLBS
  - CLC
  - CLNY.B
  - CLRBZ
  - CMG
  - CMS
  - CMU
  - CNDT
  - CNSF
  - CNY
  - CNYA
  - COR
  - CRIS
  - CRMD.WS
  - CRY
  - CRZO
  - CSCR
  - CSLT
  - CTA_A
  - CTNN
  - CUBI_C
  - CUBI_D
  - CUBI.E
  - CUPM
  - CUTR
  - CVO.NYSE
  - CWEN_A
  - CWI
  - CY
  - DCUC
  - DDMXW
  - DDR_A
  - DFVL_NASDAQ
  - DFVL.NASDAQ
  - DFVS.NASDAQ
  - DHCP.WS.B
  - DISHW
  - DJCI
  - DMDV
  - DMTX
  - DOOR
  - DPS
  - DS_B
  - DSUM
  - DTRM
  - DVHI
  - DVY.NASDAQ
  - DYII
  - DYNC
  - EASI
  - EDOM
  - EEA
  - EFAV
  - EFC
  - EFZ
  - EMEY
  - EMIS
  - EMO
  - ENG
  - ENLV
  - ENOB
  - ENTL
  - ENVE
  - EQRR
  - EQT_V
  - ERY
  - ESGR
  - ESR
  - ETON
  - EUDV
  - EUFN
  - EUFS
  - EUM
  - EVJ
  - EWA
  - EWRM
  - EWZ
  - FAD
  - FCAP
  - FCLF
  - FDBC
  - FDLO
  - FDO
  - FGEN
  - FHB
  - FIDI
  - FISR
  - FLEH
  - FPAC.U
  - FPO.A.CL
  - FRC.I
  - FRGI
  - FRME
  - FRSX
  - FSACU
  - FSBC
  - FSZ
  - FTNW
  - FTV
  - FXG
  - FXL
  - GA
  - GCOM
  - GDMA
  - GDO
  - GDP.D
  - GECCL
  - GEK
  - GGO.A
  - GGO.C
  - GGP
  - GLADN
  - GLBL
  - GLW
  - GNE.A
  - GPIAW
  - GRAF_WS
  - GRBK
  - GRNQ
  - GTES
  - GTHX
  - GWAY
  - GWGH
  - GXP_A_CL
  - HBHC
  - HCCHU
  - HEOP
  - HEUV
  - HLAL
  - HLF
  - HLG
  - HLIO
  - HMI
  - HMTA
  - HMTV
  - HNGR
  - HOG
  - HPOL
  - HRI
  - HVB
  - HVPW
  - HWCPL
  - HYF
  - IAC
  - IBCC
  - IBHE
  - IBMQ
  - IDI
  - IEUR
  - IFEU
  - IFN
  - IGC.WS
  - IGHG
  - III
  - IIIN
  - IMDZ
  - IMUC.WS
  - INCO
  - ...
  - INY
  - IPB
  - IRM
  - IRT_NYSE
  - ISL
  - IVENC
  - IXG
  - IXSE
  - JBJ
  - JHEM
  - JLS
  - JMBA
  - JMPC
  - JPM_F
  - JUNO
  - KAR
  - KBAL
  - KBWD
  - KEY
  - KIORQ
  - KKR_A
  - KLCD
  - KLOX
  - KPFS
  - KRE
  - KRFT
  - KTOS
  - KYAK
  - KYN_G_CL
  - KYTH
  - LACQU
  - LARE
  - LBND
  - LD
  - LDI
  - LDKSY
  - LEVI
  - LFEQ
  - LGC_WS
  - LINDW
  - LIOX
  - LITB
  - LKQ
  - LLIT
  - LLSC
  - LMB
  - LNC.WS
  - LO
  - LOV
  - LTONY
  - LTS_A
  - LUNA
  - LVHE
  - MAT
  - MCC
  - MCX
  - MDLZ22
  - MDVXW
  - MEC
  - MER_E
  - MES
  - MFLR
  - MFO
  - MGH
  - MITO
  - MKC/V
  - MKC.V
  - MLA
  - MLI
  - MLPE
  - MLPG
  - MMDM
  - MNRK
  - MOG/B
  - MOLC
  - MOMO
  - MPB
  - MPX
  - MRNA
  - MS_A
  - MS.E
  - MS.I
  - MS.K
  - MSR
  - MSTR
  - MTB.CL
  - MTSL
  - MUI
  - MVG
  - MVIS
  - MVV
  - MXC
  - MXMTY
  - MXWL
  - MYF
  - N
  - NDAQ21
  - NDRA
  - NEE_N
  - NEEPC
  - NFIN
  - NGE
  - NHTC
  - NJV
  - NLY_F
  - NNBR
  - NNC
  - NOVB
  - NQI
  - NRF_B
  - NRF_C
  - NSA
  - NSA.A
  - NSLP.A
  - NSPR_WS_B
  - NSS
  - NSU
  - NTRA
  - NUTR
  - NVGS
  - NXGN
  - OAK.A
  - OCCIP
  - OEW
  - OGCP
  - OHAI
  - OMEX
  - ONSIU
  - OPESU
  - ORG
  - OSHC
  - OSN
  - OTT
  - OTTW
  - OXLCP
  - PB
  - PBI_A_CL
  - PCAR
  - PCN
  - PCTY
  - PEN
  - PFSW
  - PHIIDQ
  - PINC
  - PL
  - PMTG
  - PNC
  - PNRA
  - POST
  - PPX
  - PRE_G
  - PRGO
  - PRIF_C
  - PRSN
  - PRY_CL
  - PSA_D
  - PSA.S
  - PSA_U
  - PSA_X
  - PSB
  - PSB_U
  - PSB.Y
  - PSM
  - PSR
  - PSRL
  - PSTV
  - PUB
  - PVBC
  - PYN
  - QID
  - QQQX
  - QWLD
  - QXRR
  - RBS_L
  - RBS_N_CL
  - RBS.N.CL
  - RBS_P_CL
  - RDY
  - RECN
  - REG.G.CL
  - RFG
  - RFL
  - RGRO
  - RIT
  - RLH_A
  - RLI
  - RLM
  - RMG.U
  - RNEM
  - RSO
  - RWL
  - RWLK
  - RWM
  - RYN
  - SATS
  - SB
  - SB_D
  - SBLKL
  - SBOW.NYSE
  - SCCI
  - SCE.C
  - SCIL
  - SCYB
  - SDBT
  - SDVY
  - SFIG
  - SGOL
  - SIAL
  - SNLN
  - SNLN_NASDAQ
  - SOFO
  - SPA
  - SPNE
  - SPYG
  - SQBK
  - SRG_A
  - SRL
  - SRPT
  - SSLJ
  - SSPY
  - SSRX
  - SSTK
  - SSY
  - STAG.A
  - STAG_A_CL
  - STI
  - STLRW
  - STM
  - STR
  - STRC
  - SWM
  - SWU
  - SYNT
  - SYX
  - SZCRW
  - T
  - TACOU
  - TAI
  - TAYCP
  - TBB
  - TCF_D
  - TDACU
  - TDJ
  - TEL
  - TESO
  - TGNAW
  - TIF
  - TIPT
  - TMSRW
  - TMUS.A
  - TNP.B.CL
  - TRTY
  - TSI
  - TSO
  - TTF
  - TUR.NASDAQ
  - TUTT
  - TWLO
  - TWO
  - TWO.A
  - TYG_B_CL
  - UINF
  - VALQ
  - VALV
  - VEACU
  - VESH
  - VIFL
  - VIRT
  - VLY.A
  - VMIN
  - VNET
  - VNO
  - VONE
  - VQT
  - VR.A
  - VRD
  - VTSI
  - WAAS
  - WAG
  - WAIR
  - WBIL
  - WBIN
  - WLB
  - WLRHW
  - WP
  - WRK
  - XHR
  - XLF
  - XSPA
  - XVZ
  - XYNPW
  - YCB
  - YETI
  - YGEHY
  - YIN
  - ZDGE
  - ZEK
  - ZZ